import React, { useState } from 'react';
import Layout from '@theme/Layout';

export default function UsersPage() {
  const [search, setSearch] = useState('');

  const userData = {
    Ontologies: [

{ name: "ACGT Master Ontology (ACGT MO)", url: "http://bioportal.bioontology.org/ontologies/ACGT-MO" },
{ name: "Actionable Intelligence Retrieval System (AIRS)", url: "http://ncor.buffalo.edu/ontologies/AIRS_Ontologies.pdf" },
{ name: "Addiction Ontology (Addict-O)", url: "https://onlinelibrary.wiley.com/doi/10.1111/add.16010" },
{ name: "Additive Manufacturing Ontology (AMO)", url: "https://www.sciencedirect.com/science/article/pii/S0166361518301647" },
{ name: "Adolescent Depression Ontology (ADO)", url: "https://www.jmir.org/article/viewFile/jmir_v19i7e259/2" },
{ name: "Advanced Manufacturing Basic Entity Relationships (AMBER) ontology", url: "https://www.frontiersin.org/journals/energy-research/articles/10.3389/fenrg.2024.1356571/full" },
{ name: "Advanced Product Quality Planning (APQP) Ontology", url: "https://www.researchgate.net/publication/384062050" },
{ name: "AFO Foundational Ontology", url: "http://esw.w3.org/topic/HCLS/AFO_Foundational_Ontology" },
{ name: "African Wildlife Ontology (AWO)", url: "https://arxiv.org/pdf/1905.09519.pdf" },
{ name: "Agronomic Linked Data (AgroLD)", url: "https://www.biorxiv.org/content/10.1101/325423v3.full.pdf" },
{ name: "AGRonomy Ontology (AGRO)", url: "https://bigdata.cgiar.org/resources/agronomy-ontology/" },
{ name: "Aircraft System Ontology", url: "https://link.springer.com/article/10.1007/s10845-022-02043-7" },
{ name: "Algorithm-Implementation-Execution Ontology Design Pattern", url: "http://ontologydesignpatterns.org/wiki/images/4/41/WOP2016_paper_07.pdf" },
{ name: "Allotrope Merged Ontology Suite (AFO)", url: "https://bioportal.bioontology.org/ontologies/AFO" },
{ name: "Alzheimer Disease Ontology (ADO)", url: "http://www.sciencedirect.com/science/article/pii/S155252601300085X" },
{ name: "Alzheimer's Disease Diagnosis Ontology (ADDO)", url: "https://ma.x-mol.com/paper/1366901247607140352" },
{ name: "Anatomy of the Insect Skeleto-Muscular system ontology (AISM)", url: "https://www.preprints.org/manuscript/202201.0254/v1" },
{ name: "Animals in Context Ontology (ACO)", url: "http://ceur-ws.org/Vol-897/session1-paper04.pdf" },
{ name: "Anthropological Notation Ontology (ANNO)", url: "https://www.semantic-web-journal.net/system/files/swj3553.pdf" },
{ name: "Antimicrobial-Microorganism Ontology", url: "https://www.sciencedirect.com/science/article/pii/S1532046411001675" },
{ name: "Apollo Structured Vocabulary (Apollo-SV)", url: "http://jbiomedsem.biomedcentral.com/articles/10.1186/s13326-016-0092-y" },
{ name: "Argument Ontology (ARGO)", url: "https://github.com/johnbeve/Argument-Ontology" },
{ name: "ARIES (Arkansas Imaging Enterprise System) Knowledge Graph", url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8866818/" },
{ name: "Assessment of Indian Economy During Covid-19 (INBANCIDO)", url: "https://bioportal.bioontology.org/ontologies/INBANCIDO" },
{ name: "Asset Management Ontology (AMODO)", url: "https://www.sciencedirect.com/science/article/abs/pii/S2452414X21000947" },
{ name: "Autism-DSM-ADI-R Ontology (ADAR)", url: "http://www.ncbi.nlm.nih.gov/pubmed/26151311" },
{ name: "Bacterial Clinical Infectious Diseases Ontology (BCIDO)", url: "http://www.sciencedirect.com/science/article/pii/S1532046415001549" },
{ name: "Baden Württemberg Materials Digital Domain Ontology (BWMD)", url: "https://matportal.org/ontologies/BWMD-DOMAIN" },
{ name: "Baden Württemberg Materials Digital Mid Ontology (BWMD-MID Ontology)", url: "https://matportal.org/ontologies/BWMD-MID" },
{ name: "Bank Ontology", url: "http://world-comp.org/p2011/IKE5165.pdf" },
{ name: "Barcant Butterfly Collection (BBC) ontology", url: "https://essay.utwente.nl/104562/1/VijayKumar_MA_EEMCS.pdf" },
{ name: "Battery Electric Vehicle Charging Infrastructure Ontology", url: "https://www.utwente.nl/en/eemcs/fois2024/resources/papers/ruiz-et-al-a-battery-electric-vehicle-charging-infrastructure-ontology-for-interdisciplinary-research.pdf" },
{ name: "Battle Management Ontology (BMO)", url: "http://link.springer.com/article/10.1007/s10489-016-0834-7" },
{ name: "Bayesian Verification Ontology Stack", url: "https://ieeexplore.ieee.org/abstract/document/10521072?casa_token=dnlOWzWSHmgAAAAA:P7u_v3JB33qMvTRP4He41l3UD69GX45HXS84htwIqPPZPhtSEwJFAovknNKxqnJ2VzLOoBM0" },
{ name: "Behavior Change Intervention Ontology (BCIO)", url: "https://wellcomeopenresearch.org/articles/5-123" },
{ name: "Behaviour Change Technique Ontology", url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10427801/" },
{ name: "Behavior Perspective Model (BPM)", url: "https://books.google.com/books?hl=en&lr=lang_en&id=u8xmCgAAQBAJ&oi=fnd&pg=PA366&ots=p35Xg1rqn0&sig=6VibTWt8Y6mpTSyPFFc68xHePDw#v=onepage&f=false" },
{ name: "Beta Cell Genomics Application Ontology (BCGO)", url: "http://obofoundry.org/ontology/bcgo.html" },
{ name: "Bio-Knowledge Network Ontology (BioKNO)", url: "https://www.degruyter.com/view/journals/jib/15/3/article-20180023.xml" },
{ name: "BioAssay Ontology", url: "http://www.bioassayontology.org/" },
{ name: "BioGateway (BGW)", url: "https://academic.oup.com/nar/advance-article/doi/10.1093/nar/gkae566/7706482" },
{ name: "Bioinformatics Web Service Ontology (OBIWS)", url: "https://github.com/obi-webservice/OBIws" },
{ name: "The Biomarker Ontology (BMONT)", url: "https://bioportal.bioontology.org/ontologies/BMONT" },
{ name: "Biomedical Burden Ontology (BBO)", url: "https://ceur-ws.org/Vol-3939/paper1.pdf" },
{ name: "Biomedical Ethics Ontology", url: "http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2725426/" },
{ name: "Biomedical Grid Terminology (BiomedGT, retired)", url: "https://wiki.nci.nih.gov/pages/viewpage.action?pageId=63996208" },
{ name: "Biomedical Study - Lifecycle Management (BMS-LM) core ontology", url: "https://doi.org/10.1016/j.jbi.2022.104007" },
{ name: "Biomimetic Ontology", url: "https://www.mdpi.com/2313-7673/10/1/39" },
{ name: "BioTop", url: "http://ebooks.iospress.nl/publication/46379" },
{ name: "Body Fluids Ontology (BFLO)", url: "http://ontology.buffalo.edu/smith/articles/BFLO_ICBO_2011.pdf" },
{ name: "Bone Dysplasia Ontology (BDO)", url: "http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3338382/" },
{ name: "Building Information Management (BIM) domain ontology", url: "https://www.mdpi.com/2076-3417/13/8/4859" },
{ name: "Brain Injury Knowledge Ontology (BIKO)", url: "https://www.biorxiv.org/content/10.1101/2023.10.29.564650v1.full.pdf" },
{ name: "Brinell Test Ontology-BFO (BTO-BFO)", url: "https://bioportal.bioontology.org/ontologies/BTO-BFO" },
{ name: "BWMD Domain Ontology", url: "https://matportal.org/ontologies/BWMD-DOMAIN" },
{ name: "BWMD Mid-Level Ontology", url: "https://matportal.org/ontologies/BWMD-MID" },
{ name: "BWMD Original Non-Modularized Ontology", url: "https://matportal.org/ontologies/BWMD" },
{ name: "Cancer Cell Ontology (OncoCL)", url: "http://ceur-ws.org/Vol-1060/icbo2013_submission_75.pdf" },
{ name: "Cancer Chemoprevention Ontology (CanCo)", url: "http://bioportal.bioontology.org/ontologies/CANCO" },
{ name: "Cardiovascular Disease Ontology (CVDO)", url: "https://www.ebi.ac.uk/ols/ontologies/cvdo" },
{ name: "Case Based Reasoning (CBR) Ontology", url: "https://doi.org/10.1109/ISSE51541.2021.9582535" },
{ name: "Categorical Temporal Phenomenology", url: "http://www.roentgensemiotics.net/phenomenology.htm" },
{ name: "Causal Pathway Ontology", url: "https://www.researchprotocols.org/2022/5/e34990" },
{ name: "Cell Behavior Ontology (CBO)", url: "http://cbo.biocomplexity.indiana.edu/" },
{ name: "Cell Culture Ontology (CCONT)", url: "https://bioportal.bioontology.org/ontologies/CCONT" },
{ name: "Cell Cycle Ontology", url: "https://genomebiology.biomedcentral.com/articles/10.1186/gb-2009-10-5-r58" },
{ name: "Cell Expression, Localization, Development and Anatomy Ontology (CELDA)", url: "http://nar.oxfordjournals.org.gate.lib.buffalo.edu/content/early/2013/12/03/nar.gkt1264.full.pdf" },
{ name: "Cell Line Ontology (CLO)", url: "http://obofoundry.org/ontology/clo.html" },
{ name: "Cellular Microscopy Phenotype Ontology (CMPO)", url: "http://jbiomedsem.biomedcentral.com/articles/10.1186/s13326-016-0074-0" },
{ name: "Character Computing Ontology (CCOnto)", url: "https://www.researchgate.net/publication/350106623_CCOnto_The_Character_Computing_Ontology" },
{ name: "CHEBI Integrated Role Ontology (CHIRO)", url: "https://obofoundry.org/ontology/chiro" },
{ name: "Chemical Analysis Ontology (CAO)", url: "http://champ-project.org/" },
{ name: "Chemical Entities of Biological Interest (ChEBI)", url: "http://www.ebi.ac.uk/chebi" },
{ name: "Chemical Information Ontology (CHEMINF)", url: "http://obofoundry.org/ontology/cheminf.html" },
{ name: "Chemical Methods Ontology (CHMO)", url: "http://obofoundry.org/ontology/chmo.html" },
{ name: "Children's Health Exposure Analysis Resource (CHEAR)", url: "https://www.ptfcehs.niehs.nih.gov/featured-resources/childrens-health-exposure-analysis-resource" },
{ name: "Cholangiocarcinoma Ontology (CCAO)", url: "https://www.proquest.com/openview/abd4e0fb97c94e8b18a78f626a9aad22/" },
{ name: "Chromatin Regulator Ontology (CHRO)", url: "https://bioportal.bioontology.org/ontologies/CHRO" },
{ name: "CHRONIOUS Ontology Suite", url: "http://ceur-ws.org/Vol-833/paper22.pdf" },
{ name: "Cigarette Smoke Exposure Ontology (CSEO)", url: "http://www.jbiomedsem.com/content/pdf/2041-1480-5-31.pdf" },
{ name: "Climate System Ontology (CSO)", url: "https://www.intechopen.com/chapters/86794" },
{ name: "Clinical Data Integration Model (CDMO)", url: "https://www.ncbi.nlm.nih.gov/pubmed/24954896" },
{ name: "Clinical LABoratory Ontology (LABO)", url: "https://bioportal.bioontology.org/ontologies/LABO" },
{ name: "Clinical Process Modelling Ontology (CPMO)", url: "https://link.springer.com/chapter/10.1007/978-3-031-34344-5_42" },
{ name: "Clinical Narrative Temporal Relation Ontology (CNTRO)", url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3248753/?" },
{ name: "Clinical Trial Protocol Ontology (CTP-O)", url: "https://www.sciencedirect.com/science/article/pii/S1569190X18301114" },
{ name: "Clusters of Orthologous Groups (COG) Analysis Ontology (CAO)", url: "https://bioportal.bioontology.org/ontologies/CAO" },
{ name: "Cognition-Guided Surgery (CGS) Ontology", url: "http://archiv.ub.uni-heidelberg.de/volltextserver/22579" },
{ name: "Cognitive Digital Twin (CDT) Ontology Framework", url: "https://www.sciencedirect.com/science/article/pii/S1755581724000932" },
{ name: "Cognitive Process Ontology (CPO)", url: "https://github.com/CommonCoreOntology/CognitiveProcessOntology" },
{ name: "Cognitive Twin (CT) Ontology", url: "https://www.sciencedirect.com/science/article/pii/S2405896322021383" },
{ name: "Collaborative Learning Healthcare Systems (CLHS) ontology", url: "https://onlinelibrary.wiley.com/doi/full/10.1002/lrh2.10306" },
{ name: "Collembola Anatomy Ontology (CLAO)", url: "https://www.scielo.br/j/babt/a/ZppjVp8tPy7sRYks4MKRynR/" },
{ name: "COMFOCUS ontology for food consumer science", url: "https://research.wur.nl/en/publications/developing-a-comprehensive-ontology-for-food-consumer-science-ins" },
{ name: "Common Anatomy Reference Ontology (CARO)", url: "http://obofoundry.org/ontology/caro.html" },
{ name: "Common Core Cyber Ontology (C3O)", url: "https://www-spiedigitallibrary-org.gate.lib.buffalo.edu/conference-proceedings-of-spie/10635/106350F/A-common-core-based-cyber-ontology-in-support-of-cross/10.1117/12.2307719.full?SSO=1" },
{ name: "Common Core Ontologies (CCO)", url: "https://github.com/CommonCoreOntology/" },
{ name: "Common Space Systems Ontology (CoSSO)", url: "https://doi.org/10.1109/AERO55745.2023.10115927" },
{ name: "Communication Standards Ontology (CSO)", url: "http://www.ncbi.nlm.nih.gov/pubmed/20543345" },
{ name: "Comparative Data Analysis Ontology (CDAO)", url: "https://bioportal.bioontology.org/ontologies/CDAO" },
{ name: "Compliance and Reward Ontology (CaRO)", url: "https://doi.org/10.1016/j.jbi.2024.104655" },
{ name: "Computational Neuroscience Ontology (CNO)", url: "https://bioportal.bioontology.org/ontologies/CNO" },
{ name: "Computer Aided Engineering Modeling Language (CAEML) Ontology", url: "https://www.clics-network.org/downloads/NAFEMS_2016_Towards%20Cognitive%20Computer%20Aided%20Engineering.pdf" },
{ name: "Computer-Based Patient Record Ontology (CPRO)", url: "https://code.google.com/archive/p/cpr-ontology/" },
{ name: "Conceptual Model Ontology (CMO)", url: "http://ceur-ws.org/Vol-833/paper25.pdf" },
{ name: "Core Data Integration Model (CDIM)", url: "https://www.researchgate.net/publication/263323866_Clinical_Data_Integration_Model_Core_Interoperability_Ontology_for_Research_Using_Primary_Care_Data" },
{ name: "Core Ontology for Biology and Biomedicine", url: "https://obofoundry.org/ontology/cob.html" },
{ name: "Core Ontology for Describing Production Equipment (OCore)", url: "https://doi.org/10.3390/asi5050098" },
{ name: "Coriell Cell Line Ontology", url: "http://efo.sourceforge.net/coriell.htm" },
{ name: "COVID-19 Infectious Disease Ontology (IDO-COVID-19)", url: "https://bioportal.bioontology.org/ontologies/IDO-COVID-19" },
{ name: "COVID-19 Ontology (COVID-19)", url: "https://bioportal.bioontology.org/ontologies/COVID-19" },
{ name: "CPR Ontology for the Institute of Medicine's (IOM) Computer-Based Patient Record Ontology", url: "http://ceur-ws.org/Vol-833/paper28.pdf" },
{ name: "Critical Minerals Ontology (CMO)", url: "https://www.sciencedirect.com/science/article/pii/S2590197424000144" },
{ name: "Crop Planning and Production Process Ontology (C3PO)", url: "http://ceur-ws.org/Vol-2969/paper12-IFOW.pdf" },
{ name: "Cultural Heritage Objects Patrimonialization Ontology (HOpatr)", url: "https://www.inf.ufrgs.br/ontobras/wp-content/uploads/2024/10/ontobras_2024_paper_10.pdf" },
{ name: "Culture, Race, Ethnicity, and Nationality Ontology (CRENO)", url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10283130/" },
{ name: "Cognitive Digital Twin Ontology for CyberSecurity (Cybonto)", url: "https://arxiv.org/pdf/2108.00551.pdf" },
{ name: "Cyber Information Ontology", url: "https://www.utwente.nl/en/eemcs/fois2024/resources/papers/limbaugh-beverley-towards-a-cyber-information-ontology.pdf" },
{ name: "Cybonto Conceptual Framework", url: "https://xmed.jmir.org/2022/2/e33502" },
{ name: "D3FEND-CCO Mapping (D3CO)", url: "https://github.com/d3fend/d3fend-ontology/blob/develop/src/ontology/mappings/d3fend-cco.ttl" },
{ name: "Dairy Cattle Performance Ontology (DCPO)", url: "http://ceur-ws.org/Vol-3073/paper3.pdf" },
{ name: "Darwin Core", url: "https://www.researchgate.net/publication/385870348_Use_Cases_Help_to_Identify_Primary_Concepts_in_Biodiversity_Information_Modeling" },
{ name: "Data Collection Ontology (GDCO)", url: "https://bioportal.bioontology.org/ontologies/GDCO" },
{ name: "Data Integration Aggregated Model for Nuclear Deployment (DIAMOND)", url: "https://www.osti.gov/biblio/1616713" },
{ name: "Data Model for Representing Biographical Information for Prosopography (Bio-CRM)", url: "https://seco.cs.aalto.fi/publications/2018/tuominen-et-al-rrl-2018.pdf" },
{ name: "Data Set Knowledge Graph (DSKG)", url: "https://github.com/michaelfaerber/data-set-knowledge-graph/tree/0aa6750a21027d7e6c13522114f6e62aa0dc35f7" },
{ name: "Data Use Ontology (DUO)", url: "http://www.obofoundry.org/ontology/duo.html" },
{ name: "Decision Ontology", url: "https://doi.org/10.3390/systems6040046" },
{ name: "Decision Support System for Liver Disease Prediction", url: "https://arxiv.org/ftp/arxiv/papers/2311/2311.07595.pdf" },
{ name: "Deontic Ontology", url: "https://ceur-ws.org/Vol-2137/ws_SoLe_paper_1.pdf" },
{ name: "Diabetes mellitus Diagnosis Ontology (DDO)", url: "http://link.springer.com/article/10.1186/s40535-016-0021-2" },
{ name: "Diabetes Mellitus Treatment Ontology (DMTO)", url: "https://jbiomedsem.biomedcentral.com/articles/10.1186/s13326-018-0176-y" },
{ name: "Digital Construction Ontologies (DiCon) Suite", url: "https://digitalconstruction.github.io/v/0.5/" },
{ name: "Digital Engineering Framework for Integration and Interoperability (DEFII)", url: "https://arxiv.org/ftp/arxiv/papers/2206/2206.10454.pdf" },
{ name: "Digital Objects in Philosophy Ontology (DOPHO)", url: "https://publiscologne.th-koeln.de/frontdoor/deliver/index/docId/1363/file/MAT_Seidlmayer.pdf" },
{ name: "Digital Twin Ontology", url: "https://ceur-ws.org/Vol-3882/fomi-4.pdf" },
{ name: "Digital Twin Ontology Framework for Manufacturing", url: "https://link.springer.com/chapter/10.1007/978-3-031-43666-6_22" },
{ name: "Digital Twin Network", url: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3945058" },
{ name: "Disaster Management Ontology (DMO)", url: "https://doi.org/10.1038/s41598-023-34874-6" },
{ name: "Document Act Ontology (D-Acts)", url: "https://code.google.com/p/d-acts" },
{ name: "Drosophila Phenotype Ontology (DPO)", url: "https://jbiomedsem.biomedcentral.com/articles/10.1186/2041-1480-4-30" },
{ name: "Drug Database for Inborn Errors of Metabolism Ontology (DDIEM)", url: "http://ddiem.phenomebrowser.net/" },
{ name: "Drug Interaction Ontology (DIO)", url: "http://www.ncbi.nlm.nih.gov/pubmed/15360854" },
{ name: "Drug Ontology (DrOn)", url: "http://obofoundry.org/ontology/dron.html" },
{ name: "Drug Repurposing Ontology (DRO)", url: "https://www.researchgate.net/profile/Werner_Ceusters/publication/335079148_Foundations_for_a_Realism-based_Drug_Repurposing_Ontology/links/5d4d7ce44585153e5948eb68/Foundations-for-a-Realism-based-Drug-Repurposing-Ontology.pdf" },
{ name: "Drug-drug Interaction Evidence Ontology (DIDEO)", url: "http://obofoundry.org/ontology/dideo.html" },
{ name: "Drug-drug Interaction Ontology (DINTO)", url: "http://www.obofoundry.org/ontology/dinto.html" },
{ name: "E-Cigarette Ontology (E-CigO)", url: "https://doi.org/10.1111/add.16010" },
{ name: "Eagle-I Research Resource Ontology (ERO)", url: "https://open.med.harvard.edu/wiki/display/eaglei/Ontology" },
{ name: "Echinoderm Anatomy and Development Ontology (ECAO)", url: "https://bioportal.bioontology.org/ontologies/ECAO" },
{ name: "The Ecosystem Ontology (ECSO)", url: "https://bioportal.bioontology.org/ontologies/ECSO" },
{ name: "EifcOWL (Enhanced Ontology for the Construction Industry Foundation Classes)", url: "https://content.iospress.com/articles/applied-ontology/ao210254" },
{ name: "Electrocardiography Ontology (ECG)", url: "http://www.j-biomed-inform.com/article/S1532-0464(10)00118-8/abstract" },
{ name: "ELECTRICA Ontology", url: "https://link.springer.com/chapter/10.1007/978-3-031-77792-9_16" },
{ name: "Eligibility Criteria Ontology (EC-O)", url: "https://www.sciencedirect.com/science/article/pii/S1569190X18301114" },
{ name: "Email Ontology", url: "http://ncor.buffalo.edu/2013/STIDS/5-Email.pptx" },
{ name: "Emotion Ontology (EMO)", url: "http://www.obofoundry.org/ontology/mfoem.html" },
{ name: "ENanoMapper (ENM)", url: "https://github.com/enanomapper" },
{ name: "End of Life (EoL) Domain Ontology", url: "https://www.sciencedirect.com/science/article/abs/pii/S0167739X19326640" },
{ name: "Energy System Ontology (ESO)", url: "https://iris.cnr.it/retrieve/8d03906c-a93e-487a-9f00-df4f608c7b4d/gEneSys%20-%20D.1.1%20-%20Systematic%20literature%20review%20of%20the%20studies%20at%20the%20nexus%20of%20gender%20equality%20and%20sustainable%20energy%20systems%20and%20ontology%20of%20energy%20systems-3.pdf" },
{ name: "Engineering-to-BioMimetic Ontology (E2BMO)", url: "https://www.mdpi.com/2411-9660/2/4/53" },
{ name: "Environmental Control and Life Support System (ECLSS) Ontology", url: "https://ieeexplore.ieee.org/abstract/document/10115927" },
{ name: "ENVOn (3D shape ontology)", url: "http://www.semantic-web-journal.net/system/files/swj3043.pdf" },
{ name: "Epidemiology Ontology (EPO)", url: "http://obofoundry.org/ontology/epo.html" },
{ name: "Epigenome Ontology (EGO)", url: "https://bioportal.bioontology.org/ontologies/EGO" },
{ name: "Epilepsy and Seizure Ontology (EPSO)", url: "http://www.ncbi.nlm.nih.gov/pubmed/23686934" },
{ name: "EpilepsyOntology (EPIO)", url: "https://www.researchsquare.com/article/rs-1259791/v1" },
{ name: "Ethically Driven Robotics and Automation Systems (ERAS) Ontology", url: "https://www.mdpi.com/2075-4426/13/8/1209" },
{ name: "Ethnicity Ontology (EO)", url: "https://bioportal.bioontology.org/ontologies/EO" },
{ name: "European Materials Modeling Ontology (EMMO)", url: "https://emmc.info/wp-content/uploads/2017/12/EMMC_IntOp2017-Cambridge_Ghedini_Bologna.pdf" },
{ name: "Event-Based Functional Behavior Ontology (EFBO)", url: "http://ceur-ws.org/Vol-1660/caos-paper2.pdf" },
{ name: "Event-Based Ontology for Historical Description (EOHD)", url: "https://www.emeraldinsight.com/doi/abs/10.1108/DLP-02-2018-0005" },
{ name: "Evolution Ontology (EO)", url: "https://code.google.com/archive/p/evolution-ontology/" },
{ name: "Exercise Medicine Ontology (EXMO)", url: "https://www.nature.com/articles/s41597-024-04217-9" },
{ name: "(EXperimental ACTions) Biomedical Protocol Ontology (EXACT2)", url: "http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4255744" },
{ name: "Experimental Factor Ontology (EFO)", url: "http://www.ebi.ac.uk/efo" },
{ name: "Exposé", url: "https://lirias.kuleuven.be/bitstream/123456789/273222/1/sokd10.pdf" },
{ name: "eXtended Formal Ontology (XFO)", url: "https://www.researchgate.net/profile/Robert_Allen5/publication/325141757_XFO_Toward_Programming_Rich_Semantic_Models/links/5afa473d458515c00b6bd24f/XFO-Toward-Programming-Rich-Semantic-Models.pdf?origin=publication_detail" },
{ name: "FAO/Bioversity Multi-Crop Passport Descriptors Ontology (MCPDO)", url: "https://d197for5662m48.cloudfront.net/documents/publicationstatus/247636/preprint_pdf/07755e3929fe0d382ec6927469298c8c.pdf" },
{ name: "FASTO Ontology (incorporates BFO, FHIR, CPG,and SSN)", url: "https://bioportal.bioontology.org/ontologies/FASTO" },
{ name: "Fatigue Test Ontology (FTO)", url: "https://onlinelibrary.wiley.com/doi/pdf/10.1002/adem.202400675" },
{ name: "Feedback Intervention Ontology (FIO)", url: "https://github.com/Display-Lab" },
{ name: "Financial Documents Ontology (FIN)", url: "http://ceur-ws.org/Vol-2969/paper57-SoLEE.pdf" },
{ name: "Fission Yeast Phenotype Ontology (FYPO)", url: "http://www.pombase.org/documentation/gene-page-phenotypes" },
{ name: "Flower-Visiting Domain Ontology (FV)", url: "http://www.sciencedirect.com/science/article/pii/S157495411400082X" },
{ name: "Known Flower-Visiting Group Domain Ontology (KFG)", url: "http://www.sciencedirect.com/science/article/pii/S157495411400082X" },
{ name: "Flower-Visiting Behavior Application Ontology (FVB)", url: "http://www.sciencedirect.com/science/article/pii/S157495411400082X" },
{ name: "Observation-Date Application Ontology (OBD)", url: "http://www.sciencedirect.com/science/article/pii/S157495411400082X" },
{ name: "Flybase Drosophila Anatomy Ontology (DAO)", url: "http://obofoundry.org/ontology/fbbt.html" },
{ name: "Flybase Drosophila Phenotype Ontology (FYPO)", url: "http://obofoundry.org/ontology/fypo.html" },
{ name: "Food Ontology (FoodOn)", url: "http://obofoundry.org/ontology/foodon.html" },
{ name: "Food Recipe Ingredient Substitution Ontology (FRISO)", url: "https://doi.org/10.3390/s22031095" },
{ name: "Food-Energy-Water Systems Ontology (FEWsONT)", url: "https://www.liebertpub.com/doi/full/10.1089/ees.2018.0551" },
{ name: "Foundational Model of Anatomy (FMA)", url: "http://obofoundry.org/ontology/fma.html" },
{ name: "Framework for Semantic Workflow Composition in the Geology Domain", url: "http://ceur-ws.org/Vol-2228/abstract6.pdf" },
{ name: "FuTRES Ontology of Vertebrate Traits (FOVT)", url: "https://github.com/futres/fovt" },
{ name: "Gastrointestinal Endoscopy Ontology (GIEO)", url: "http://ceur-ws.org/Vol-833/paper36.pdf" },
{ name: "Gender, Sex, and Sexual Orientation (GSSO) ontology", url: "https://academic-oup-com.gate.lib.buffalo.edu/jamia/advance-article-abstract/doi/10.1093/jamia/ocaa061/5858296" },
{ name: "Gene Ontology (GO)", url: "http://obofoundry.org/ontology/go.html" },
{ name: "Gene Regulation Ontology (GRO)", url: "https://ub-madoc.bib.uni-mannheim.de/35191/1/dissertation_beisswanger.pdf" },
{ name: "General Information Model (GIM)", url: "http://jamia.bmj.com/content/20/5/986.full" },
{ name: "Genesis Ontology", url: "https://doi.org/10.1093/bioadv/vbad102" },
{ name: "GENIAL! Basic Ontology (GBO)", url: "https://github.com/wawrzik/GENIALOntologies" },
{ name: "Genomic Feature and Variation Ontology (GFVO)", url: "https://peerj.com/articles/933/" },
{ name: "Genomics Integrated Biobanking Ontology (GIBO)", url: "https://github.com/Nits11/GIBO" },
{ name: "Genotype Ontology (GENO)", url: "https://bioportal.bioontology.org/ontologies/GENO" },
{ name: "GeoCore Geology Ontology", url: "https://www.lume.ufrgs.br/bitstream/handle/10183/225741/001129935.pdf" },
{ name: "GeoFault Ontology", url: "https://doi.org/10.1016/j.cageo.2023.105478" },
{ name: "Geographical Entity Ontology (GEO)", url: "http://www.obofoundry.org/ontology/geo.html" },
{ name: "Geological Spatial Relations Ontology", url: "https://github.com/BDI-UFRGS/GeologicalSpatialRelationsOntology" },
{ name: "GeoReservoir ontology for deep-marine depositional system geometry", url: "https://www.sciencedirect.com/science/article/pii/S0098300421002880" },
{ name: "GeoSPARQL", url: "https://opengeospatial.github.io/ogc-geosparql/geosparql11/spec.pdf" },
{ name: "Gestalt", url: "https://ieeexplore.ieee.org/abstract/document/6956738" },
{ name: "Global Code Book Ontology (GCBO)", url: "https://bioportal.bioontology.org/ontologies/GCBO" },
{ name: "Global Electronic Health Record Ontology (G-EHR-O)", url: "https://www.sciencedirect.com/science/article/pii/S1569190X18301114" },
{ name: "Glyco-Enzyme Pathway and Molecular Function Ontology (GlycoEnzOnto)", url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9750110/" },
{ name: "Graphs, Objects, Points, Properties, Roles, and Relationships Ontology (GOPPRRE)", url: "https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9534721" },
{ name: "Ground Vehicle Simulation Modeling Ontology (GVSMO)", url: "https://ndia-mich.org/images/events/gvsets/2024/papers/DE%20SE/1%2030PM%20GVSMO%20-%20An%20Ontology%20for%20the%20Simulation%20Modeling%20of%20Ground%20Vehicles.pdf" },
{ name: "Healthy City (HC) Ontology", url: "https://doi.org/10.3390/su132413844" },
{ name: "Health Data Ontology Trunk (HDOT)", url: "http://purl.org/hdot" },
{ name: "Health Surveillance Ontology (HSO)", url: "https://bioportal.bioontology.org/ontologies/HSO" },
{ name: "Hemocomponents and Hemoderivatives Ontology (HEMONTO)", url: "http://mba.eci.ufmg.br/downloads/ontobras-2013_paper1.pdf" },
{ name: "Hercules Network of Ontologies (ROH)", url: "https://dspacecris.eurocris.org/bitstream/11366/2478/2/EUNIS2023_VIVO_AGuillaumet_paper71.pdf" },
{ name: "HERMES 4D Printing Ontology", url: "https://www.sciencedirect.com/science/article/pii/S0264127521007486" },
{ name: "Homeostasis Imbalance Process Ontology (HoIP)", url: "https://www.biorxiv.org/content/10.1101/2023.03.09.531883v1.full.pdf" },
{ name: "Host Pathogen Interactions Ontology (HPO)", url: "http://bioportal.bioontology.org/ontologies/HPIO?p=classes" },
{ name: "Human Activity and Infrastructure Foundry (HAIF)", url: "https://arxiv.org/ftp/arxiv/papers/1809/1809.09548.pdf" },
{ name: "Human Disease Ontology (DOID)", url: "http://www.obofoundry.org/ontology/doid.html" },
{ name: "Human Experience Realist Ontology (HERO)", url: "https://www.researchgate.net/publication/316557588_A_Human_Experience_Realist_Ontology_in_Basic_Formal_Ontology" },
{ name: "Human Interaction Network Ontology (HINO)", url: "http://arxiv.org/pdf/1311.3355.pdf" },
{ name: "Human Physiology Simulation Ontology (HuPSON)", url: "http://www.jbiomedsem.com/content/pdf/2041-1480-4-35.pdf" },
{ name: "Hypertension Ontology (HTN)", url: "https://bioportal.bioontology.org/ontologies/HTN" },
{ name: "IDEAS expAnded wiTh BCIO (SATO)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9975785/" },
{ name: "Imaging Biomarker Ontology (IBO)", url: "https://bioportal.bioontology.org/ontologies/IBO" },
{ name: "Incose Digital Engineering Information Exchange (DEIX) Ontology", url: "https://www.engr.colostate.edu/~drherber/files/Ontology%20Development%20with%20Prot%C3%A9g%C3%A9.pdf" },
{ name: "Industrial Data Ontology (IDO)", url: "https://www.iso.org/standard/87560.html" },
{ name: "Industrial Ontologies Foundry (IOF) Core Ontology", url: "http://ceur-ws.org/Vol-3240/paper3.pdf" },
{ name: "Industrial Ontology Foundry (IOF) Maintenance Reference Ontology", url: "https://spec.industrialontologies.org/ontology/maintenance/MaintenanceReferenceOntology/" },
{ name: "Industrial Production Workflow Ontologies (InPro)", url: "https://doi.org/10.1016/j.aei.2023.102185" },
{ name: "Industry 4.0 Field Device (I40FD) ontology", url: "https://sensorsportal.com/p_3342.html" },
{ name: "Industry Skills and Professions Ontology (ISPO)", url: "https://link.springer.com/chapter/10.1007/978-3-319-99707-0_40" },
{ name: "Infectious Disease Ontology", url: "http://obofoundry.org/ontology/ido.html" },
{ name: "International Classification of Diseases Ontology (ICDO)", url: "https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04402-2" },
{ name: "uc_Eating", url: "https://github.com/IC-FOODS/uc_Eating" },
{ name: "uc_FoodDrugInteractionOntology", url: "https://github.com/IC-FOODS/uc_FoodDrugInteractionOntology" },
{ name: "uc_Milk", url: "https://github.com/IC-FOODS/uc_Milk" },
{ name: "uc_Processing", url: "https://github.com/IC-FOODS/uc_Processing" },
{ name: "uc_Sense", url: "https://github.com/IC-FOODS/uc_Sense" },
{ name: "Interoperability and Integration Framework (IoIF)", url: "https://doi.org/10.3390/systems6040046" },
{ name: "Intervention Population Ontology (IPO)", url: "https://wellcomeopenresearch.org/articles/10-122" },
{ name: "Intervention Setting Ontology", url: "https://wellcomeopenresearch.org/articles/5-124" },
{ name: "Intracranial Aneurysm (ICA) Ontology", url: "http://www.sciencedirect.com/science/article/pii/S1532046415000519" },
{ name: "Intraoperative Neurophysiological Monitoring Document Ontology (IOMDO)", url: "https://www.researchsquare.com/article/rs-2026582/v1" },
{ name: "Invasion Biology Ontology (INBIO)", url: "https://bioportal.bioontology.org/ontologies/INBIO" },
{ name: "IoT-based Management of Infectious Disease Ontology (IoT-MIDO)", url: "https://formative.jmir.org/2024/1/e53711" },
{ name: "ISA Infrastructure for the Biosciences", url: "https://agbeltran.github.io/talks/2013-02-27-cshals" },
{ name: "Iranian Traditional Medicine General Ontology (IrGO)", url: "https://jbiomedsem.biomedcentral.com/articles/10.1186/s13326-021-00237-1" },
{ name: "Joining Process Ontology (JPO)", url: "https://link.springer.com/chapter/10.1007/978-981-99-8819-8_45" },
{ name: "Kidney Tissue Atlas Ontology (KTAO)", url: "https://bioportal.bioontology.org/ontologies/KTAO" },
{ name: "Kinship Ontology", url: "https://hal.science/hal-03996128/document" },
{ name: "Knowledge-Augmented Maintenance Model for Sustainable Manufacturing (KARMA)", url: "http://www.referent-tracking.com/RTU/files/Rabenberg-Pengput-Ceusters-ICBO2023-for-publication.pdf" },
{ name: "Knowledge Base Of Biomedicine (KaBOB)", url: "http://www.biomedcentral.com/content/pdf/s12859-015-0559-3.pdf" },
{ name: "Knowledge Graph for Dementia (DemKG)", url: "https://www.mdpi.com/2076-3417/13/18/10497" },
{ name: "Knowledge Graph Generation Framework for Systems Engineering (KGG4SE)", url: "https://www.semantic-web-journal.net/system/files/swj3844.pdf" },
{ name: "Knowledge Object Implementation Ontology (KOIO)", url: "https://riojournal.com/article/109307/" },
{ name: "Knowledge Object Reference Ontology (KORO)", url: "https://onlinelibrary.wiley.com/doi/full/10.1002/lrh2.10054" },
{ name: "Laser Powder Bed Fusion Ontology (LPBFO)", url: "https://matportal.org/ontologies/LPBFO" },
{ name: "Levee System Ontology (LSO)", url: "https://doi.org/10.5194/egusphere-egu23-16768" },
{ name: "Library of Integrated Network-based Cellular Signatures", url: "https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-017-1981-5" },
{ name: "Life Cycle Assessment (LCA) Ontology", url: "https://link.springer.com/chapter/10.1007/978-3-031-43688-8_35" },
{ name: "Life Ontology (LIFO)", url: "https://bioportal.bioontology.org/ontologies/LIFO" },
{ name: "Lipid Ontology", url: "http://obofoundry.org/ontology/lipro.html" },
{ name: "Literary Theme Ontology (LTO)", url: "https://www.researchgate.net/publication/332832296_The_Literary_Theme_Ontology_for_Media_Annotation_and_Information_Retrieval" },
{ name: "Lung Cancer Ontology (LCO)", url: "https://www.sciencedirect.com/science/article/abs/pii/S1532046425000371?via%3Dihub" },
{ name: "Machine Learning Schema (ML-Schema) ontology", url: "https://openreview.net/pdf?id=B1e8MrXVxQ" },
{ name: "Magnetic Resonance Imaging Acquisition and Analysis Ontology (MRIO)", url: "https://link.springer.com/article/10.1007/s12021-024-09664-8" },
{ name: "Maintainability Design Ontology for Complex prOducts (MDOCO)", url: "https://doi.org/10.1016/j.compind.2024.104124" },
{ name: "Maintenance Activity Reference Ontology", url: "http://www.semantic-web-journal.net/system/files/swj3067.pdf" },
{ name: "Maintenance Motion State Sequence Ontology (MMSSO)", url: "https://www.sciencedirect.com/science/article/abs/pii/S2452414X24001031" },
{ name: "Maintenance Work Order (MWO) ontology", url: "https://www.semantic-web-journal.net/content/ontology-maintenance-activities-and-its-application-data-quality-1" },
{ name: "Major histocompatibility complex (MHC) Restriction Ontology (MRO)", url: "http://obofoundry.org/ontology/mro.html" },
{ name: "Malaria Ontology (IDOMAL)", url: "http://obofoundry.org/ontology/idomal.html" },
{ name: "Mammalian Feeding Muscle Ontology (MFMO)", url: "https://bioportal.bioontology.org/ontologies/MFMO" },
{ name: "Manufacturing Process Ontology (MPO)", url: "https://doi.org/10.1016/j.compind.2024.104101" },
{ name: "Manufacturing Service Description Language (MSDL) ontology", url: "https://doi.org/10.1115/detc2006-99600" },
{ name: "Manufacturing Supply Chain Ontology (MSCO)", url: "https://buffalo.box.com/s/rbapg73v4jq18dvw0rf2jnszndvnxmb0" },
{ name: "Materials Data Science (MDS) Ontology", url: "https://matportal.org/ontologies/MDS" },
{ name: "Material Science and Engineering Ontology (MSEO)", url: "https://matportal.org/ontologies/MSEO" },
{ name: "Matwerk Ontology (MWO)", url: "https://nfdi-matwerk.pages. rwth-aachen.de/ta-oms/mwo/docs/index.htm" },
{ name: "Mechanical Testing Ontology (MTO)", url: "https://doi.org/10.1016/j.compind.2023.104016" },
{ name: "Mechanisms of Action (MoA) Ontology", url: "https://wellcomeopenresearch.org/articles/8-337/v2" },
{ name: "Medical Action Ontology (MAxO)", url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10370244/" },
{ name: "Medical Imaging and Diagnostic Ontology (MIDO)", url: "https://bioportal.bioontology.org/ontologies/MIDO?p=classes" },
{ name: "Medication Adherence Behavior Ontology (MAB-Ontology)", url: "https://scholarworks.iupui.edu/bitstream/handle/1805/17767/Sawesi_iupui_0104D_10326.pdf" },
{ name: "MFO Mental Disease Ontology (MFO-MD)", url: "http://obofoundry.org/ontology/mfomd.html" },
{ name: "Mental Functioning Ontology (MF)", url: "http://obofoundry.org/ontology/mf.html" },
{ name: "Mental Health Ontology (MHO)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11729156/" },
{ name: "Microbiology Ontology (MicrO)", url: "http://jbiomedsem.biomedcentral.com/articles/10.1186/s13326-016-0060-6" },
{ name: "Microbial Conditions Ontology (MCO)", url: "https://bioportal.bioontology.org/ontologies/MCO" },
{ name: "(Microbial) Typing Ontology (TypOn)", url: "http://www.phyloviz.net/typon" },
{ name: "Middle Layer Ontology for Clinical Care (MLOCC)", url: "http://p-medicine.eu/project/wp-4" },
{ name: "Military Ontology", url: "http://basic-formal-ontology.org/publications#salmen" },
{ name: "Military Scenario Ontology (MSO)", url: "http://link.springer.com/article/10.1007/s10489-016-0834-7" },
{ name: "Minimum Information Model for Patient Safety (MIMPS)", url: "http://www.ncbi.nlm.nih.gov/pubmed/27139388" },
{ name: "Minimum PDDI Information Ontology (MPIO)", url: "https://www.ebi.ac.uk/ols4/ontologies/mpio" },
{ name: "miRNAO: an Ontology Unfolding the Domain of microRNAs", url: "http://iwbbio.ugr.es/2014/papers/IWBBIO_2014_paper_103.pdf" },
{ name: "MIRO and IRbase", url: "http://www.plosntds.org/article/info:doi/10.1371/journal.pntd.0000465" },
{ name: "Mission and Means Framework (MMF) Ontology", url: "https://ieeexplore.ieee.org/abstract/document/8455742/" },
{ name: "Mixture of Domain (MoD) Ontologies", url: "https://www.mdpi.com/2075-5309/15/1/133" },
{ name: "MOCA (Multi-attribute Ontology-based Criticality Analysis)", url: "https://link.springer.com/article/10.1007/s43684-022-00021-7" },
{ name: "Modal Relation Ontology (MRO)", url: "https://www.spiedigitallibrary.org/conference-proceedings-of-spie/10635/106350H/Problems-with-prescriptions--disentangling-data-about-actual-versus-prescribed/10.1117/12.2307718.short?SSO=1" },
{ name: "Mode of Delivery (MoD) Ontology", url: "https://wellcomeopenresearch.org/articles/5-125" },
{ name: "Model Card Report Ontology (MCRO)", url: "https://doi.org/10.1186/s12859-022-04797-6" },
{ name: "Model for Clinical Information (MCI)", url: "http://bmcmedinformdecismak.biomedcentral.com/articles/10.1186/s12911-016-0248-9" },
{ name: "Model for Describing Insect Anatomical Structures (MoDIAS)", url: "https://www.preprints.org/manuscript/202201.0254/v1" },
{ name: "Modern Conflict Ontology (MCO)", url: "https://link.springer.com/book/10.1007/978-3-030-53214-7" },
{ name: "Modular Environmental Modeling Ontology (MEMOn)", url: "https://linkinghub.elsevier.com/retrieve/pii/S1364815218301221" },
{ name: "Modular Maintenance Ontology (IOF-MAINT)", url: "https://arxiv.org/pdf/2404.05224.pdf" },
{ name: "Molecular Process Ontology (MOP)", url: "http://purl.obolibrary.org/obo/MOP_0000079" },
{ name: "Mouse Pathology Ontology (MPATH)", url: "http://obofoundry.org/ontology/mpath.html" },
{ name: "Multiple Aspects Maintenance Ontology (MuAMO)", url: "https://doi.org/10.1017/S0890060423000215" },
{ name: "Name Reaction Ontology (RXNO)", url: "http://obofoundry.org/ontology/rxno.html" },
{ name: "Nanoparticle Ontology (NPO)", url: "http://www.ncbi.nlm.nih.gov/pubmed/20211274" },
{ name: "Nanoparticles Impact on Human Cell morphology Ontology (NIHCO)", url: "https://www.bjbabe.ro/wp-content/uploads/2017/10/18_RODINO.pdf" },
{ name: "National Research Data Infrastructure for Data Science Ontology (NFDI4DSO)", url: "https://arxiv.org/pdf/2408.08698" },
{ name: "Neurodegenerative Disease Data Ontology (NDDO)", url: "https://doi.org/10.1007/978-3-030-33778-0_19" },
{ name: "Neomark Oral Cancer Ontology (NEOMARK4)", url: "https://bioportal.bioontology.org/ontologies/NEOMARK4" },
{ name: "Neural Electromagnetic Ontologies (NEMO)", url: "https://www.nitrc.org/projects/nemo" },
{ name: "Neural Electronic Interface Ontology", url: "https://bioportal.bioontology.org/ontologies/NEIO" },
{ name: "Neuron Phenotype Ontology (NPOKB)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9547803/" },
{ name: "Neuropsychological Integrative Ontology (NIO)", url: "https://bioportal.bioontology.org/ontologies/NIO" },
{ name: "NeuroPsychological Testing Ontology (NPT)", url: "http://www.unbsj.ca/sase/csas/data/ws/icbo2013/papers/research/icbo2013_submission_31.pdf" },
{ name: "Neuroscience Information Framework", url: "http://www.neuinfo.org/" },
{ name: "Neuroscience Information Framework Cell Ontology (NIFCELL)", url: "https://bioportal.bioontology.org/ontologies/NIFCELL" },
{ name: "Neuroscience Information Framework Dysfunction Ontology (NIFDYS)", url: "https://bioportal.bioontology.org/ontologies/NIFDYS" },
{ name: "Neuroscience Information Framework Standard Ontology (NIFSTD)", url: "http://bioportal.bioontology.org/ontologies/NIFSTD" },
{ name: "NFDIcore 2.0 (German) National Research Data Infrastructure ontology", url: "https://arxiv.org/pdf/2410.01821" },
{ name: "NIMS Polymer Database (PoLyInfo) Ontology", url: "https://www.tandfonline.com/doi/full/10.1080/27660400.2024.2354651" },
{ name: "NLighten Ontology (NLN)", url: "https://bioportal.bioontology.org/ontologies/NLN" },
{ name: "NMDC Ontology (NMDCO)", url: "https://bioportal.bioontology.org/ontologies/NMDCO" },
{ name: "NMR-Controlled Vocabulary (NMR)", url: "https://bioportal.bioontology.org/ontologies/NMR" },
{ name: "NMR-Instrument Component of Metabolomics Investigations Ontology", url: "http://bioportal.bioontology.org/ontologies/NMR?p=classes&conceptid=root" },
{ name: "Non-Coding RNA Ontology (NCRO)", url: "http://soc.southalabama.edu/~huang/papers/BIBM-15-1.pdf" },
{ name: "Nuclear Design Ontology", url: "https://link.springer.com/chapter/10.1007/978-3-030-82083-1_2" },
{ name: "OBDMR: An Ontology-Based Data Model for Railways", url: "https://doi.org/10.1166/jctn.2020.8662" },
{ name: "OBR Scolio (scoliosis) ontology", url: "https://www.sciencedirect.com/science/article/pii/S0169260719300665" },
{ name: "OCD Ontology (OCD)", url: "https://bioportal.bioontology.org/ontologies/OCD" },
{ name: "Ocular Disease Ontology (ODO)", url: "http://www.unbsj.ca/sase/csas/data/ws/icbo2013/papers/posters/icbo2013_submission_67.pdf" },
{ name: "Ocular Immune-Mediated Inflammatory Diseases Ontology (OcIMIDo)", url: "https://www.sciencedirect.com/science/article/pii/S001048252100336X" },
{ name: "The Occupation Ontology (OccO)", url: "https://github.com/Occupation-Ontology/OccO" },
{ name: "Offshore Petroleum Production Plant Ontology (O3PO)", url: "https://www.sciencedirect.com/science/article/abs/pii/S0957417423026064" },
{ name: "OncoCL-KB", url: "http://ceur-ws.org/Vol-1546/poster_65.pdf" },
{ name: "OntoAlign++", url: "http://ceur-ws.org/Vol-1041/ontobras-2013_paper52.pdf" },
{ name: "OntoBuildableSpace Ontology", url: "https://doi.org/10.1007/978-3-031-37189-9_30" },
{ name: "OntoDM Core", url: "https://www.researchgate.net/publication/271952542_Ontology_of_core_data_mining_entities" },
{ name: "OntoForInfoScience", url: "http://www2.marilia.unesp.br/revistas/index.php/bjis/article/viewFile/5426/3970" },
{ name: "Ontologies for Representing Surgical Procedure Models (OntoSPM)", url: "https://ontospm.univ-rennes1.fr/doku.php?id=ontology" },
{ name: "Ontologies for the Emergency Road Vehicle Domain", url: "https://arxiv.org/pdf/2406.15268" },
{ name: "Ontologized Minimum Information About BIobank data Sharing (OMIABIS)", url: "http://obofoundry.org/ontology/omiabis.html" },
{ name: "Ontology Based Clinical Decision Support System for Geriatrics", url: "https://www.ingentaconnect.com/contentone/asp/jctn/2020/00000017/00000001/art00042" },
{ name: "Ontology-Based Data Access (OBDA)", url: "http://www.sciencedirect.com.gate.lib.buffalo.edu/science/article/pii/S1570826815000165" },
{ name: "Ontology Based Decision Support System for Tuberculosis Management and Control", url: "https://www.researchgate.net/publication/312296048" },
{ name: "Ontology-Based Editor for Manuscript Transcription and Annotation", url: "https://doi.org/10.1007/978-981-99-9836-4_18" },
{ name: "Ontology-Based eXtensible Data Model (OBX)", url: "http://www.ncbi.nlm.nih.gov/pubmed/20460173" },
{ name: "Ontology-Based Generation of Causal Graphs (CGs)", url: "https://doi.org/10.3390/make6020042" },
{ name: "Ontology-Driven Information System (ODIS)/Ontology-Driven Scenario Generator (ODSG)", url: "http://www.sciencedirect.com/science/article/pii/S0952197615000913" },
{ name: "Ontology for Adverse Events (OAE)", url: "http://obofoundry.org/ontology/oae.html" },
{ name: "Ontology for Autism Spectrum Disorder", url: "http://www.sciencedirect.com/science/article/pii/S1532046415001367" },
{ name: "Ontology for Biobanking (OBIB)", url: "http://obofoundry.org/ontology/obib.html" },
{ name: "Ontology for Biofilms (BIFO)", url: "https://doi.ieeecomputersociety.org/10.1109/BIBM58861.2023.10385562" },
{ name: "Ontology for Biomedical Investigations (OBI)", url: "http://obofoundry.org/ontology/obi.html" },
{ name: "The Ontology for Biomedical Investigation based Inner Ear Electrophysiology (OBI_IEE)", url: "https://bioportal.bioontology.org/ontologies/OBI_IEE" },
{ name: "Ontology for Cancer research variables (OCRV)", url: "https://bmcmedinformdecismak.biomedcentral.com/articles/10.1186/s12911-018-0636-4" },
{ name: "Ontology for Computable Eligibility Criteria - Hepatitis C Virus (OCEC-HCV)", url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6371316/" },
{ name: "Ontology for Dengue Fever (IDODEN)", url: "http://journals.plos.org/plosntds/article?id=10.1371/journal.pntd.0003479" },
{ name: "Ontology for Documentation of Variable/Data Source Selection (ODVDS)", url: "http://ceur-ws.org/Vol-2427/SEPDA_2019_paper_15.pdf" },
{ name: "Ontology for Drug Discovery Investigations (DDI)", url: "https://code.google.com/archive/p/ddi-ontology/" },
{ name: "Ontology for ELEctronic tool for Clinicians, Trainers and Researchers In Child Abuse (ELECTRICA)", url: "https://bioportal.bioontology.org/ontologies/ELECTRICA" },
{ name: "Ontology for Energy Investigations (OEI)", url: "https://www.researchgate.net/publication/234128482_Facilitating_Knowledge_Sharing_and_Analysis_in_Energy_Informatics_with_the_Ontology_for_Energy_Investigations_%28OEI%29" },
{ name: "Ontology for Functionally Graded Materials (OFGM)", url: "https://www.academia.edu/27922525/Development_of_a_Manufacturing_Ontology_for_Functionally_Graded_Materials" },
{ name: "Ontology for General Medical Science (OGMS)", url: "http://obofoundry.org/ontology/ogms.html" },
{ name: "Ontology for Genes and Genomes - Mouse (OGG-MM)", url: "http://www.ontobee.org/ontology/OGG-Mm" },
{ name: "Ontology for Genetic Interval (OGI)", url: "http://bioportal.bioontology.org/ontologies/OGI?p=classes&conceptid=root" },
{ name: "Ontology for Genetic Susceptibility Factor (OGSF)", url: "http://obofoundry.org/ontology/ogsf.html" },
{ name: "Ontology for Guiding Appropriate Antibiotic Prescribing", url: "http://www.sciencedirect.com/science/article/pii/S1532046411001675" },
{ name: "Ontology for Information Science (OntoforInforScience)", url: "https://www.researchgate.net/publication/299534658_OntoforInfoScience_a_detailed_methodology_for_construction_of_ontologies_and_its_application_in_the_blood_domain" },
{ name: "Ontology for Laparoscopic Surgeries (LapOntoSPM)", url: "http://link.springer.com/article/10.1007/s11548-015-1222-1" },
{ name: "Ontology for MIcroRNA Target Prediction (OMIT)", url: "http://obofoundry.org/ontology/omit.html" },
{ name: "Ontology for Newborn Screening and Translational Research (ONSTR)", url: "https://www.researchgate.net/publication/256648393_%27ONSTR_The_Ontology_for_Newborn_Screening_Follow-up_and_Translational_Research%27" },
{ name: "Ontology for Next Generation Sequencing Experiments (NGS Ontology)", url: "https://github.com/lindenb/ngs-ontology" },
{ name: "Ontology for Nutritional Epidemiology (ONE)", url: "https://obofoundry.org/ontology/one.html" },
{ name: "Ontology for Nutritional Studies (ONS)", url: "https://genesandnutrition.biomedcentral.com/articles/10.1186/s12263-018-0601-y" },
{ name: "Ontology for Pain and Related Disability, Mental Health and Quality of Life (OPMQoL)", url: "http://www.referent-tracking.com/RTU/?page=projects.phtml#opmqol" },
{ name: "Ontology for Parasite LifeCycle (OPL)", url: "http://obofoundry.org/ontology/opl.html" },
{ name: "Ontology for Periodontitis (PERIO)", url: "http://www.jbiomedsem.com/content/6/1/30" },
{ name: "Ontology for Petroleum Production", url: "https://hozo.jp/ISWC2023_PD-Industry-proc/ISWC2023_paper_436.pdf" },
{ name: "Ontology for Prognostic Health Management (PHM) in Spacecraft Avionics", url: "https://hozo.jp/ISWC2023_PD-Industry-proc/ISWC2023_paper_436.pdf" },
{ name: "Ontology for Radiation Therapy (RTO)", url: "https://www.iccr2024.org/papers/526229.pdf" },
{ name: "Ontology for Representing CDM Semantics (ORCS)", url: "https://bioportal.bioontology.org/ontologies/ORCS" },
{ name: "Ontology for Stem Cell Investigations (OSCI)", url: "https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-019-2723-7" },
{ name: "Ontology for the Description of Scientific Research Data (Metadate4Ing)", url: "https://www.mdpi.com/2227-9717/12/3/597" },
{ name: "Ontology for the Documentation of Variable Selection and Data source Selection and Integration (OD-ATTEST)", url: "https://papers.phmsociety.org/index.php/phmconf/article/download/3195/phmc_22_3195" },
{ name: "Ontology for the prevention of digital crimes against children", url: "https://ceur-ws.org/Vol-3905/master4.pdf" },
{ name: "Ontology for the Study of Biofilms (BIFO)", url: "https://doi.org/10.1109/BIBM58861.2023.10385562" },
{ name: "Ontology for Thoracentesis", url: "https://www.sciencedirect.com/science/article/pii/S0933365717301525" },
{ name: "Ontology of Autonomous Driving Based on the SAE J3016 Standard", url: "https://www.semantic-web-journal.net/system/files/swj3493.pdf" },
{ name: "Ontology of Arthropod Circulatory Systems (OArCS)", url: "http://obofoundry.org/ontology/oarcs.html" },
{ name: "Ontology of Biological and Clinical Statistics (OBCS)", url: "http://obofoundry.org/ontology/obcs.html" },
{ name: "Ontology of Biological Attributes (OBA)", url: "https://bioportal.bioontology.org/ontologies/OBA" },
{ name: "Ontology of Bipolar Disorders (OBD)", url: "https://link.springer.com/chapter/10.1007/978-3-031-75599-6_13" },
{ name: "Ontology of Cancer Related Social-Ecological Variables (OCRSEV)", url: "http://ceur-ws.org/Vol-2137/ws_ONCONTO_paper_3.pdf" },
{ name: "Ontology of Card Sleights", url: "https://arxiv.org/abs/1903.08523" },
{ name: "Ontology of Cardiovascular Drug Adverse Events (OCVDAE)", url: "https://www.nature.com/articles/s41598-017-12580-4" },
{ name: "Ontology of Chinese Medicine for Rheumatism (OCMR)", url: "https://bioportal.bioontology.org/ontologies/OCMR" },
{ name: "Ontology of Clinical Research (OCRe)", url: "https://ce.google.com/archive/p/ontology-of-clinical-research/" },
{ name: "Ontology of Commercial Exchange (OCE)", url: "https://philarchive.org/archive/MERCCC" },
{ name: "Ontology of Core Data Mining Entities (OntoDM-CORE)", url: "https://bioportal.bioontology.org/ontologies/ONTODM-CORE" },
{ name: "Ontology of Datatypes (OntoDT)", url: "https://www.sciencedirect.com/science/article/pii/S0020025515005800" },
{ name: "Ontology of Drug Adverse Events Events (ODAE)", url: "https://bioportal.bioontology.org/ontologies/ODAE" },
{ name: "Ontology of Drug Neuropathy Adverse Events (ODNAE)", url: "https://bioportal.bioontology.org/ontologies/ODNAE" },
{ name: "Ontology of Electronics (OOE)", url: "https://github.com/ontology-of-electronics" },
{ name: "Ontology of Experimental Variables and Values (OOEVV)", url: "https://bioportal.bioontology.org/ontologies/OOEVV" },
{ name: "Ontology of Genes and Genomes (OGG)", url: "http://obofoundry.org/ontology/ogg.html" },
{ name: "Ontology of Genetic Disease Investigations (OGDI)", url: "https://bioportal.bioontology.org/ontologies/OGDI" },
{ name: "Ontology of Hemotherapy (HEMONTO)", url: "https://1library.net/document/q5946wgz-hemocomponents-hemoderivatives-ontology-hemonto-ontology-blood-components.html" },
{ name: "Ontology of Host-Microbe Interactions (OHMI)", url: "https://jbiomedsem.biomedcentral.com/articles/10.1186/s13326-019-0217-1" },
{ name: "Ontology of Host-Pathogen Interactions (OHPI)", url: "https://obofoundry.org/ontology/ohpi" },
{ name: "Ontology of Laboratory Animal Medicine (OLAM)", url: "https://bioportal.bioontology.org/ontologies/OLAM" },
{ name: "Ontology of Medical Microbiology (OntoMic)", url: "http://rali.iro.umontreal.ca/rali/sites/default/files/publis/Levreault-MSc.pdf" },
{ name: "Ontology of Medically Related Social Entities (OMRSE)", url: "http://obofoundry.org/ontology/omrse.html" },
{ name: "Ontology of Microbial Phenotypes (OMP)", url: "http://obofoundry.org/ontology/omp.html" },
{ name: "Ontology of Organizational Structures of Trauma systems and Trauma centers (OOSTT)", url: "http://ceur-ws.org/Vol-1747/IT504_ICBO2016.pdf" },
{ name: "Ontology of Phenomenological Psychopathology (OPheP)", url: "https://doi.org/10.1016/S2215-0366(22)00156-0" },
{ name: "Ontology of Precision Medicine and Investigation (OPMI)", url: "https://bioportal.bioontology.org/ontologies/OPMI" },
{ name: "Ontology of RNA Sequencing (ORNASEQ)", url: "https://bioportal.bioontology.org/ontologies/ORNASEQ" },
{ name: "Ontology of Social Participation (OPS)", url: "http://arxiv.org/pdf/1501.02662.pdf" },
{ name: "Ontology of Tobacco, Nicotine and Vaping Products", url: "https://onlinelibrary.wiley.com/doi/10.1111/add.16010" },
{ name: "Ontology of Systems Engineering", url: "https://www.sciencedirect.com/science/article/pii/S1877050919307380" },
{ name: "Ontology of Vaccine Adverse Events (OVAE)", url: "http://obofoundry.org/ontology/ovae.html" },
{ name: "OntoURL", url: "https://arxiv.org/pdf/2505.11031" },
{ name: "Open Energy Ontology (OEO)", url: "https://openenergy-platform.org/ontology/oeo" },
{ name: "Open Model-Based Engineering Environment (OpenMBEE)", url: "https://link.springer.com/chapter/10.1007/978-3-030-82083-1_56" },
{ name: "Operational Environment Ontology (OEO)", url: "https://jsou.libguides.com/ld.php?content_id=37534351" },
{ name: "Optimization Algorithm Benchmarking Ontology (OPTION-ONTOLOGY)", url: "https://arxiv.org/pdf/2211.11332" },
{ name: "Oral Health and Disease Ontology (OHD)", url: "http://obofoundry.org/ontology/ohd.html" },
{ name: "Orbital Verification Ontology Stack (OVOS)", url: "https://arc.aiaa.org/doi/10.2514/6.2024-0483" },
{ name: "Organization Ontology Based on ROR", url: "https://figshare.com/articles/presentation/An_Organization_Ontology_based_on_ROR/14839359" },
{ name: "ORMA+ Ontology for Reliability Centered Maintenance", url: "https://www.politesi.polimi.it/bitstream/10589/195722/3/2022_10_Ghedini.pdf" },
{ name: "PACIFIC Cardiology Ontology", url: "https://doi.org/10.1016/j.jbi.2023.104579" },
{ name: "Parasite Experiment Ontology (PEO)", url: "http://bioportal.bioontology.org/ontologies/1335" },
{ name: "Part-Focused Manufacturing Process Ontology (PMPO)", url: "https://www.tandfonline.com/doi/abs/10.1080/0951192X.2017.1357837" },
{ name: "Pathogen Host Interaction Phenotype Ontology (PHIPO)", url: "https://bioportal.bioontology.org/ontologies/PHIPO" },
{ name: "Patient Safetry Categorial Structure (PS-CAST)", url: "http://person.hst.aau.dk/ska/MIE2015/Papers/SHTI210-0160.pdf" },
{ name: "Performance Summary Display Ontology (PSDO)", url: "https://github.com/Display-Lab/psdo" },
{ name: "Petrochemical Ontology", url: "http://books.google.com/books?id=XYOBAusxPCcC&pg=PA27" },
{ name: "PetroKGraph", url: "https://github.com/Petroles/PetroNLP" },
{ name: "Petroleum Geoimage Ontology", url: "https://ceur-ws.org/Vol-2519/paper2.pdf" },
{ name: "PGxO Pharmacogenomics Ontology", url: "https://www.biorxiv.org/content/biorxiv/early/2018/08/13/390971.full.pdf" },
{ name: "Phenotypic Quality Ontology (PaTO)", url: "http://obofoundry.org/ontology/pato.html" },
{ name: "Photovoltaic Ontology (PVO)", url: "https://doi.org/10.1109/SEGE55279.2022.9889768" },
{ name: "Physics-Based Simulation Ontology (PSO-Physics and PSO-Sim)", url: "https://www.tandfonline.com/doi/abs/10.1080/09544828.2019.1644301?journalCode=cjen20" },
{ name: "Planarian Anatomy and Developmental Stage Ontology (PLANA)", url: "https://bioportal.bioontology.org/ontologies/PLANA" },
{ name: "Planarian Phenotype Ontology (PLANP)", url: "https://bioportal.bioontology.org/ontologies/PLANP" },
{ name: "Plant Experimental Assay Ontology (PEAO)", url: "http://bioportal.bioontology.org/ontologies/PEAO" },
{ name: "Plant Ontology (PO)", url: "http://obofoundry.org/ontology/po.html" },
{ name: "Plant Phenology Ontology (PPO)", url: "https://bioportal.bioontology.org/ontologies/PPO" },
{ name: "Plant Stress Ontology (PLANTSO)", url: "https://bioportal.bioontology.org/ontologies/PLANTSO" },
{ name: "Plastic Rock Deformation (PRD) ontology", url: "https://www-sciencedirect-com.gate.lib.buffalo.edu/science/article/pii/S0098300416308482" },
{ name: "Platform Material Digital Core Ontology (PMDCo)", url: "https://onlinelibrary.wiley.com/doi/pdf/10.1002/adem.202402149" },
{ name: "Pneumonia Diagnosis Ontology (PNADO)", url: "https://bioportal.bioontology.org/ontologies/PNADO" },
{ name: "Pneumonia Ontology", url: "https://www.researchgate.net/publication/328171801" },
{ name: "PO2/TransformON", url: "https://www.nature.com/articles/s41538-023-00221-2" },
{ name: "POLARISC Emergency Response System Ontology", url: "https://www.researchgate.net/publication/332810691" },
{ name: "Polymat (Polymer Membrance research) ontology", url: "https://ceur-ws.org/Vol-3760/paper6.pdf" },
{ name: "Ponte Ontology Platform (PONTE)", url: "https://www.sciencedirect.com/science/article/pii/S1569190X18301114" },
{ name: "Population and Community Ontology (PCO)", url: "http://obofoundry.org/ontology/pco.html" },
{ name: "Population Health Record (PopHR)", url: "http://onlinelibrary.wiley.com/doi/10.1111/nyas.13271/full" },
{ name: "Porifera Ontology (PORO)", url: "http://obofoundry.org/ontology/poro.html" },
{ name: "Pre-Eclampsia Ontology (PEO)", url: "http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0162828" },
{ name: "Precision Medicine Ontology (PMO)", url: "http://www.aimspress.com/fileOther/PDF/MBE/mbe-17-04-227.pdf" },
{ name: "PreOptique Platform for Integrated Pre-surgery Reports", url: "https://jbiomedsem.biomedcentral.com/articles/10.1186/s13326-019-0197-1" },
{ name: "Prescription of Drugs Ontology (PDRO)", url: "https://pdfs.semanticscholar.org/7100/59ad86c5c2ef7a5b1430d30a8950a88aa319.pdf" },
{ name: "Printing Information Modelling Ontology (PIM-O)", url: "https://www.mdpi.com/2076-3417/13/23/12664" },
{ name: "PRISM: A Platform for Imaging inPrecision Medicine", url: "https://ascopubs.org/doi/pdfdirect/10.1200/CCI.20.00001" },
{ name: "Process and Observation Ontology (PO2)", url: "https://www.sciencedirect.com/science/article/abs/pii/S0958694619300032" },
{ name: "Process Chemistry Ontology", url: "https://github.com/proco-ontology/PROCO" },
{ name: "Product Life Cycle Ontology for Additive Manufacturing", url: "https://www.sciencedirect.com/science/article/pii/S0166361518301647" },
{ name: "PRoduct ONTOlogy (PRONTO)", url: "https://www.researchgate.net/profile/Gabriela-Henning/publication/372413019_Redefining_PRoduct_ONTOlogy_to_improve_intra_and_cross-domain_interoperability" },
{ name: "Product Service System (PSS) Ontology", url: "https://www.sciencedirect.com/science/article/abs/pii/S0166361522001269?via%3Dihub" },
{ name: "Proper Name Ontology (PNO)", url: "https://code.google.com/p/proper-name-ontology" },
{ name: "PROSPECT-IDR: Personalised Prediction of Infectious Disease Risk", url: "http://www.tara.tcd.ie/bitstream/handle/2262/86059/Final%20Version.pdf?sequence=1" },
{ name: "Protein Conformation Ontology (PRC)", url: "https://ceur-ws.org/Vol-3726/paper4.pdf" },
{ name: "Protein Ontology (PRO)", url: "http://obofoundry.org/ontology/pr.html" },
{ name: "Protein-Ligand Interaction Ontology (PLIO)", url: "http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3106195" },
{ name: "Provenir ontology for provenance modeling", url: "https://corescholar.libraries.wright.edu/cgi/viewcontent.cgi?article=1079&context=knoesis" },
{ name: "Provisional Cell Ontology (PCL)", url: "https://bioportal.bioontology.org/ontologies/PCL" },
{ name: "Public Safety and Emergency Management (PS/EM) Communications Ontology", url: "https://www.ida.org/-/media/feature/publications/p/pu/public-safety-and-emergency-management-communications-ontology/d-8583.ashx" },
{ name: "QROWD urban traffic and mobility ontology", url: "https://ec.europa.eu/research/participants/documents/downloadPublic?documentIds=080166e5c077764d&appId=PPGMS" },
{ name: "Quality of Service (QoS) Ontology", url: "https://www.researchgate.net/publication/259759470" },
{ name: "Radiation Biology Ontology (RBO)", url: "https://bioportal.bioontology.org/ontologies/RBO" },
{ name: "Rare-Earth Elements (REE) Mineral System Ontology", url: "https://doi.org/10.1130/2022.2558(03)" },
{ name: "Reactions and Catalysis (Reac4Cat) ontology", url: "https://github.com/AleSteB/Reac4Cat/blob/main/reac4cat_with_examples.owl" },
{ name: "Reference Ontology for Expert-Bound Processes in Manufacturing (ROXANA)", url: "https://www.tandfonline.com/doi/full/10.1080/00207543.2024.2360086" },
{ name: "Reference Ontology for FISH", url: "http://ceur-ws.org/Vol-3235/paper25.pdf" },
{ name: "Relations Ontology (RO)", url: "http://www.obofoundry.org/ontology/ro.html" },
{ name: "Reliability Assessment for Assembly Stations (RAAS) Ontology", url: "https://infoscience.epfl.ch/record/265908/files/" },
{ name: "ReRiskOnto", url: "https://github.com/patriciaferreiradasilva/resriskonto" },
{ name: "Resilient Crisis-Relevant Supply Networks Ontology (ResKriVer)", url: "https://2023.eswc-conferences.org/wp-content/uploads/2023/05/paper_Karam_2023_A.pdf" },
{ name: "Rescue Ontology (ResOnt)", url: "https://www.researchgate.net/profile/Samer-Chehade-2/publication/353571839" },
{ name: "RFID System Configuration Ontology (RFID SCO)", url: "https://doi.org/10.1017/S0269888921000096" },
{ name: "RNA Ontology (RnaO)", url: "http://obofoundry.org/ontology/rnao.html" },
{ name: "Robotic Capability Ontology (RCO)", url: "https://ceur-ws.org/Vol-3595/paper7.pdf" },
{ name: "Rock Plastic Deformation (RPD) ontology", url: "http://www.sciencedirect.com/science/article/pii/S0098300416308482" },
{ name: "Role Ontology (ROLEO)", url: "https://bioportal.bioontology.org/ontologies/ROLEO" },
{ name: "ROMAIN industrial maintenance ontology", url: "https://www.researchgate.net/publication/332390146_ROMAIN_Towards_a_BFO_compliant_reference_ontology_for_industrial_maintenance" },
{ name: "Saliva Ontology (SALO)", url: "https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-11-302" },
{ name: "Schistosomiasis Process Ontology (IDOSCHISTO)", url: "http://ceur-ws.org/Vol-1747/IP01_ICBO2016.pdf" },
{ name: "Scientific Evidence and Provenance Information Ontology (SEPIO)", url: "http://ceur-ws.org/Vol-1747/IT605_ICBO2016.pdf" },
{ name: "Search engine Optimization Ontology (SEO)", url: "https://www.semantic-web-journal.net/system/files/swj3755.pdf" },
{ name: "Sefaria Topics", url: "https://github.com/Sefaria/Sefaria-Project/wiki/Documentation-for-Topics-Hierarchy" },
{ name: "Semantic Common Data Model (SCDM)", url: "https://www.sciencedirect.com/science/article/pii/S016926072300584" },
{ name: "Semantic Electronic Health Record (SEHR) Model", url: "http://www.linked2safety-project.eu/node/44" },
{ name: "SLACKS", url: "http://dl.acm.org/citation.cfm?id=2580238" },
{ name: "Semantic Materials Manufacturing Design (SEMMD) Ontology", url: "https://github.com/cpauloh/semmd" },
{ name: "Semantic Reference Model for Individualization of Information Processes", url: "https://www.mdpi.com/2079-9292/10/20/2523" },
{ name: "Semantic Systems Engineering Ontology (SESO)", url: "https://indico.esa.int/event/386/contributions/6243/attachments/4281/6391/1435%20-%20using%20semantic%20systems%20engineering%20techniques%20to%20verify%20the%20large%20aperture%20space%20telescope%20mission%20%E2%80%93%20current%20status.pdf" },
{ name: "Semanticscience Integrated Ontology (SIO)", url: "https://jbiomedsem.biomedcentral.com/articles/10.1186/2041-1480-5-14" },
{ name: "Senselab Ontology", url: "http://www.ncbi.nlm.nih.gov/pubmed/20006477" },
{ name: "Sentinel: Platform for Semantic Enrichment of Media Streams", url: "http://ieeexplore.ieee.org/document/8232468/" },
{ name: "Sequence Ontology (SO)", url: "http://obofoundry.org/ontology/so.html" },
{ name: "Shop-Floor Digital Twin (DT) ontology", url: "http://ceur-ws.org/Vol-2615/paper5.pdf" },
{ name: "Simple Standard for Sharing Ontological Mappings (SSSOM)", url: "https://arxiv.org/pdf/2405.05413" },
{ name: "Situated and Interactive Multimodal Conversations", url: "https://arxiv.org/pdf/2006.01460.pdf" },
{ name: "Situation Awareness Ontology (SAO)", url: "http://link.springer.com/article/10.1007/s10489-016-0834-7" },
{ name: "Sketch Map Ontology", url: "https://www.tandfonline.com/doi/abs/10.1080/13658816.2017.1309043?journalCode=tgis20" },
{ name: "Skin Physiology Ontology (SPO)", url: "https://bioportal.bioontology.org/ontologies/SPO" },
{ name: "Sleep Domain Ontology (SDO)", url: "https://bioportal.bioontology.org/ontologies/SDO" },
{ name: "SMART Protocols", url: "http://vocab.linkeddata.es/SMARTProtocols" },
{ name: "Smart Ultrasound in Obstetrics and Gynecology (SUOG) Ontology", url: "https://icbo2021.inf.unibz.it/wp-content/uploads/2021/09/169_S1_ElGhosh_paper_8.pdf" },
{ name: "SNOMED CT (SCT) Standard Ontology", url: "https://bmcmedinformdecismak.biomedcentral.com/articles/10.1186/s12911-018-0651-5" },
{ name: "Social Determinants of Health Ontology (SDoHO)", url: "https://ojphi.jmir.org/2024/1/e52845" },
{ name: "Social Psychology Ontology (SPO)", url: "https://ubir.buffalo.edu/xmlui/handle/10477/79440" },
{ name: "Socialog Ontology for Social Simulation", url: "https://www.exag.org/papers/An%20Executable%20Ontology%20for%20Social%20Simulation.pdf" },
{ name: "Software Ontology (SWO)", url: "http://jbiomedsem.biomedcentral.com/articles/10.1186/2041-1480-5-25" },
{ name: "Software, Disabilities and Competences Ontology (SODIC)", url: "http://dspace.ucuenca.edu.ec/bitstream/123456789/28548/1/Trabajo%20de%20Titulaci%C3%B3n.pdf" },
{ name: "Soil Food Web Ontology", url: "https://www.biorxiv.org/content/10.1101/2023.02.03.526812v1.full.pdf" },
{ name: "Space Domain Ontologies (SDO)", url: "https://philpapers.org/rec/COXTSD-2" },
{ name: "Space Life Sciences Ontology (SLSO)", url: "https://obofoundry.org/ontology/slso.html" },
{ name: "Space Object Ontology (SOO)", url: "https://ieeexplore.ieee.org/document/7527882" },
{ name: "Spatial Graph Adapter (SGA) Ontology Design Pattern", url: "http://www.semantic-web-journal.net/system/files/swj1582.pdf" },
{ name: "Spatial Relation Ontology", url: "http://ceur-ws.org/Vol-2728/paper3.pdf" },
{ name: "Spatiotemporal Ontology for the Administrative Units of Switzerland (SONADUS)", url: "http://www.geo.uzh.ch/dam/jcr:6c3c9ef3-6bcd-4300-86e4-9de07d3f6f37/msc_felix_gantner_2011.pdf" },
{ name: "Special Nuclear Materials Detection Ontology (SNM-DO)", url: "http://ceur-ws.org/Vol-808/STIDS2011_CR_P2_WardEtAl.pdf" },
{ name: "Statistics Ontology (STATO)", url: "http://obofoundry.org/ontology/stato.html" },
{ name: "STATO-LMM Linear Mixed Model Ontology", url: "https://www.nature.com/articles/s41597-020-0409-7" },
{ name: "Style of Delivery Ontology", url: "https://wellcomeopenresearch.org/articles/8-456" },
{ name: "Subcellular Anatomy Ontology (SAO)", url: "http://obofoundry.org/ontology/sao.html" },
{ name: "Suggested Ontology for Pharmacogenomics (SO-Pharm)", url: "http://obofoundry.org/ontology/sopharm.html" },
{ name: "Supply and Demand Open Knowledge Network (SUDOKN) ontology", url: "https://link.springer.com/chapter/10.1007/978-3-031-71637-9_21#Sec11" },
{ name: "Supply Chain Traceability Ontology", url: "https://asmedigitalcollection.asme.org/computingengineering/article-abstract/22/5/051002/1139465/Enabling-Traceability-in-Agri-Food-Supply-Chains" },
{ name: "Surface Water Ontology (SWO)", url: "https://www.usgs.gov/media/files/surface-water-ontology" },
{ name: "Survey Ontology", url: "https://www.scitepress.org/papers/2017/65827/65827.pdf" },
{ name: "Sustainability Core Ontology (SCO)", url: "https://github.com/gioUbbiali/Sustainability-Core-Ontology" },
{ name: "Sustainable Development and Climate (SDC) Ontology", url: "https://github.com/hbabaie1/Sustainable-Development-and-Climate-SDC-ontology" },
{ name: "Sustainable Meat Systems Ontology (SuMSO)", url: "https://github.com/gioUbbiali/Sustainable-Meat-Systems-Ontology" },
{ name: "Symptomatic Treatment of Multiple Sclerosis Ontology (STMSO)", url: "https://e-hir.org/upload/pdf/hir-2022-28-4-332.pdf" },
{ name: "Taxonomy for Rehabilitation of Knee Conditions (TRAK)", url: "http://users.cs.cf.ac.uk/I.Spasic/trak" },
{ name: "Terminologia Anatomica Humana", url: "https://doi.org/10.1007/s12565-024-00759-5" },
{ name: "terms4FAIRskills (T4FS)", url: "https://terms4fairskills.github.io/" },
{ name: "The Common Rule Ontology (CRO)", url: "https://github.com/CRO-ontology/CRO" },
{ name: "The Trope Ontology", url: "https://www.mdpi.com/2409-9287/4/3/40" },
{ name: "Time Event Ontology (TEO)", url: "https://bioportal.bioontology.org/ontologies/TEO" },
{ name: "Tissue and Organ Transplant Ontology (TOTO)", url: "https://docs.google.com/document/d/1iArQNIJrJ02n8KRQXlriG2mxkQVNBWzM/edit" },
{ name: "Toxic Process Ontology (TXPO)", url: "http://www.obofoundry.org/ontology/txpo.html" },
{ name: "Trade-Space Analysis Tool for Constellations (TAT-C) ontology", url: "https://arc.aiaa.org/doi/abs/10.2514/6.2019-1032" },
{ name: "Traditional Chinese Drugs Ontology (TCDO)", url: "https://www.hindawi.com/journals/ecam/2021/6637810/" },
{ name: "Translational Medicine Ontology (TMO)", url: "http://esw.w3.org/topic/HCLSIG/PharmaOntology" },
{ name: "Transportation System Ontology", url: "http://www.ontobee.org/ontology/TSO" },
{ name: "TruSpark Hyper-Automation Platform", url: "https://www.linkedin.com/pulse/pioneering-real-estate-ontological-hyper-automation-tavi-truman-ffyzc/" },
{ name: "Tumour-Node-Metastasis Ontology (TNM-O)", url: "https://jbiomedsem.biomedcentral.com/articles/10.1186/s13326-016-0106-9" },
{ name: "Uber Anatomy Ontology (UBERON)", url: "https://bioportal.bioontology.org/ontologies/UBERON" },
{ name: "UMass Engineering Core Ontologies", url: "https://www.mdpi.com/2079-8954/6/4/46/pdf" },
{ name: "United Nations SDG (Sustainable Development Goals) Ontology Framework", url: "https://iswc2017.ai.wu.ac.at/wp-content/uploads/papers/MainProceedings/179.pdf" },
{ name: "United Nations System Document Ontology (ONTO-UNDO)", url: "https://unsceb-hlcm.github.io/onto-undo/" },
{ name: "Universal Core Semantic Layer", url: "http://sunsite.informatik.rwth-aachen.de/Publications/CEUR-WS/Vol-555/paper5.pdf" },
{ name: "Vaccination Informed Consent Ontology (VICO)", url: "http://jbiomedsem.biomedcentral.com/articles/10.1186/s13326-016-0062-4" },
{ name: "Vaccine Investigation Ontology (VIO)", url: "https://bioportal.bioontology.org/ontologies/VIO" },
{ name: "Vaccine Ontology (VO)", url: "http://obofoundry.org/ontology/vo.html" },
{ name: "Value Stream Mapping (VSM) Ontology", url: "https://era.library.ualberta.ca/items/5ad997be-0f3d-4456-8108-b3c69d851a98/view/060e801a-92a5-44ac-ba8a-0a00ab22765e/Abdelghani_Mohammad_202101_PhD.pdf" },
{ name: "Vertebrate Breed Ontology (VBO)", url: "https://monarch-initiative.github.io/vertebrate-breed-ontology/" },
{ name: "Vickers Test Ontology (VTO)", url: "https://matportal.org/ontologies/VTO" },
{ name: "Viral Disease Ontology Trunk (VDOT)", url: "https://bioportal.bioontology.org/ontologies/VDOT" },
{ name: "Virtual Entity (VE) Ontology", url: "https://doi.org/10.1016/j.aei.2024.102747" },
{ name: "Virtual Materials Marketplace (VIMMP) Ontologies", url: "https://matportal.org/ontologies/VIMMP_ONTOLOGIES" },
{ name: "Virus Infectious Disease Ontology (VIDO)", url: "https://bioportal.bioontology.org/ontologies/VIDO" },
{ name: "Visual Inspection Ontology (VIO)", url: "https://data.uni-hannover.de/dataset/visual-inspection-ontology" },
{ name: "Visualized Emotion Ontology (VEO)", url: "https://bmcmedinformdecismak.biomedcentral.com/articles/10.1186/s12911-018-0634-6" },
{ name: "Vital Sign Ontology (VSO)", url: "http://ontology.buffalo.edu/smith/articles/Vital_Sign_Ontology.pdf" },
{ name: "Vector-Borne Disease (VBD) Ontology", url: "https://doi.org/10.1016/j.knosys.2023.110645" },
{ name: "VEuPathDB Ontology (EUPATH)", url: "https://bioportal.bioontology.org/ontologies/EUPATH" },
{ name: "VIVO Ontology", url: "https://openreview.net/forum?id=SkgyVa-coV" },
{ name: "VIVO-Integrated Semantic Framework (VIVO-ISF)", url: "https://bioportal.bioontology.org/ontologies/VIVO-ISF" },
{ name: "Volcanism Ontology (VO)", url: "https://scholarworks.gsu.edu/cgi/viewcontent.cgi?article=1124&context=geosciences_theses" },
{ name: "Wetland Monitoring Ontology (WMO)", url: "https://www.tandfonline.com/doi/full/10.1080/17538947.2023.2220620" },
{ name: "Wind Turbine Project", url: "https://github.com/standardgalactic/WindTurbineProject" },
{ name: "Women with Epilepsy of Child-Bearing Age Ontology (WWECA)", url: "https://bmcmedinformdecismak.biomedcentral.com/articles/10.1186/s12911-024-02509-z" },
{ name: "Xenopus Anatomy Ontology (XAO)", url: "http://obofoundry.org/ontology/xao.html" },
{ name: "Xenopus Phenotype Ontology (XPO)", url: "https://www.biorxiv.org/content/biorxiv/early/2021/11/13/2021.11.12.467727.full.pdf" },
{ name: "yOWL", url: "http://www2007.org/workshops/paper_130.pdf" },
{ name: "ZEMELA Intelligent Agriculture Platform", url: "https://ieeexplore.ieee.org/abstract/document/9627248" },
    ],

    "Institutions, Groups, Projects" : [
  
    { name: "Air Force Research Laboratory, Rome, New York", url: "https://www.afrl.af.mil" },
    { name: "Allotrope Foundation: Rethinking Scientific Data", url: "https://www.allotrope.org/" },
    { name: "Arlis", url: "https://www.arlis.org/" },
    { name: "AstraZeneca", url: "http://www.astrazeneca.com/" },
    { name: "Astrion", url: "https://www.salary.com/job/astrion/ontology-data-architect/j202401041929488109435" },
    { name: "Bentley Software, Inc.", url: null },
    { name: "Berkeley Bioinformatics Open-Source Projects (BBOP)", url: "http://berkeleybop.org/" },
    { name: "Biomedical Knowledge Engineering Lab at Seoul National University (SNU BiKE)", url: "http://bike.snu.ac.kr/" },
    { name: "Biomedical Ontologies, University of Arkansas, Medical Center, Little Rock", url: "https://medicine.uams.edu/dbmi/research-labs/boar/" },
    { name: "Boeing", url: "https://www.boeing.com/" },
    { name: "Brain Operation Database (BODB)", url: "https://pubmed.ncbi.nlm.nih.gov/24234915/" },
    { name: "Cambridge Semantics", url: "https://www.slideshare.net/camsemantics/transforming-data-management-and-time-to-insight-with-anzo-smart-data-lake" },
    { name: "Center for e-Design", url: "https://mie.umass.edu/e-design-center" },
    { name: "Certus", url: "https://www.certus.com/" },
    { name: "Clinical Information Science", url: "http://kerfors.blogspot.com" },
    { name: "Cranfield University, Bedfordshire, UK", url: "https://www.cranfield.ac.uk/" },
    { name: "CTSAconnect", url: "http://www.ctsaconnect.org/" },
    { name: "CUBRC", url: "http://www.cubrc.org/index.php/data-science-and-information-fusion/ontology/'94" },
    { name: "Darwin Core (DwC)", url: "http://rs.tdwg.org/dwc" },
    { name: "DeciSym", url: "https://www.decisym.ai/" },
    { name: "Division of Biomedical Ontology at the University at Buffalo Department of Biomedical Informatics", url: "https://medicine.buffalo.edu/departments/biomedical-informatics/divisions/biomedical-ontology.html" },
    { name: "DOQS: Data-Oriented Quality Solutions", url: "http://www.doqs.com/" },
    { name: "DSpace at NTNUA", url: "http://rportal.lib.ntnu.edu.tw/" },
    { name: "Dumontier Lab", url: "https://carleton.ca/biology/people/michel-dumontier/" },
    { name: "Ecole polytechnique federale de Lausanne (EPFL)", url: "https://people.epfl.ch/cgi-bin/people?id=105551&lang=en&cvlang=en" },
    { name: "Elsevier Smart Content Strategy", url: "http://www.elsevier.com/wps/find/authored_newsitem.cws_home/companynews05_01849" },
    { name: "eNanoMapper", url: "http://www.enanomapper.net/" },
    { name: "Extensible Neuroimaging Archive Toolkit (XNAT)", url: "http://www.aifb.kit.edu/images/e/e5/Sfb-infrastructure-spie2016.pdf" },
    { name: "Improvado", url: "https://improvado.io/" },
    { name: "Incose Digital Engineering Working Group", url: "https://www.incose.org/communities/working-groups-initiatives/digital-engineering-information-exchange" },
    { name: "Influenza Research Database (IRD)", url: "http://www.fludb.org/brc/home.spg?decorator=influenza" },
    { name: "INRIA Lorraine Research Unit", url: "https://www.inria.fr/en/centre-inria-nancy-grand-est" },
    { name: "Institute for Defense Analysis", url: "http://www.ida.org/" },
    { name: "Institute of Informatics, Federal University of Rio Grande do Sul, Porto Alegre, Brazil", url: "https://www.inf.ufrgs.br/site/en/" },
    { name: "Japan Advanced Institute of Science and Technology (JAIST)", url: "http://www.jaist.ac.jp/ks/english/" },
    { name: "Johns Hopkins University Applied Physics Lab", url: "http://www.jhuapl.edu/" },
    { name: "KadSci", url: "https://kadsci.com/" },
    { name: "Kobe University, Graduate School of Medicine, Department of Sociomedical Informatics", url: "http://www.med.kobe-u.ac.jp/" },
    { name: "L3 Data Tactics Corporation", url: "https://www.data-tactics.com/" },
    { name: "Language and Computing", url: "http://www.landcglobal.com/" },
    { name: "libryo", url: "https://libryo.com/" },
    { name: "Medical University Graz - Institute of Medical Informatics, Statistics and Documentation", url: "http://user.medunigraz.at/stefan.schulz" },
    { name: "NAAS.AI", url: "https://home.naas.ai/" },
    { name: "National Airspace System (NAS)", url: "https://ntrs.nasa.gov/citations/20250001629" },
    { name: "National Center for Multi-Source Information Fusion", url: "http://www.infofusion.buffalo.edu/" },
    { name: "OntoCAT", url: "http://www.ontocat.org/" },
    { name: "OntoCOG", url: "http://ontobat.hegroup.org/" },
    { name: "University at Buffalo Referent Tracking Unit", url: "http://www.referent-tracking.com/RTU/" },
    { name: "Open PHACTS", url: "http://www.openphacts.org/" },
    { name: "openEHR", url: "http://www.openehr.org/wiki/display/ontol/Ontologies+Home" },
    { name: "OSTHUS", url: "https://www.youtube.com/watch?v=WKuK2G-NUk8" },
    { name: "Patagonia Purpose Trust", url: "https://www.sciencedirect.com/science/article/abs/pii/S092180092300339" },
    { name: "Petrobras", url: "https://petrobras.com.br/en/home-petrobras" },
    { name: "Praxis: EMR research on interoperability and query of clinical records", url: "http://www.infor-med.com/downloads/articles_downloads/Praxis_EMR_SUNY_Interoperability_Project.pdf" },
    { name: "Raft", url: "https://teamraft.com/" },
    { name: "Raytheon Technologies (RTX)", url: "https://www.rtx.com/who-we-are/what-we-do/flight" },
    { name: "Roche", url: "https://www.roche.com/" },
    { name: "RocketUrBiz", url: "https://www.rocketurbiz.com/" },
    { name: "REMINE", url: "https://pubmed.ncbi.nlm.nih.gov/21057717/" },
    { name: "Saitama University - Faculty of Liberal Arts", url: "http://www.saitama-u.ac.jp/" },
    { name: "Science Applications International Corporation (SAIC)", url: "https://www.saic.com/" },
    { name: "ScienceCast", url: "https://www.sciencecast.org/" },
    { name: "Securboration", url: "http://www.securboration.com/" },
    { name: "Semantic Arts", url: "https://www.semanticarts.com/a-bfo-ready-version-of-gist/" },
    { name: "Scania", url: "https://www.scania.com/" },
    { name: "Science Commons", url: "http://www.sciencecommons.org/" },
    { name: "Summit Knowledge Solutions", url: "https://sks.ai/" },
    { name: "Neurocommons", url: "http://www.sciencecommons.org/projects/data/" },
    { name: "SMART Protocols", url: "http://www.swat4ls.org/wp-content/uploads/2015/10/SWAT4LS_2015_paper_15.pdf" },
    { name: "Thermo Fisher Scientific", url: "https://www.thermofisher.com/us/en/home.html" },
    { name: "TRADOC Operational Environment Center", url: "http://basic-formal-ontology.org/www.tradoc.army.mil/g2/oetsc/videoTBOC_flv.aspx" },
    { name: "U.S. Geological Survey (USGS) - Center of Excellence for Geospatial Information Science (CEGIS)", url: "https://www.usgs.gov/search?keywords=ontology" },
    { name: "University of Arizona Stack (UOAS)", url: "https://iafastro.directory/iac/paper/id/88366/abstract-pdf/IAC-24,D5,2,8,x88366.brief.pdf?2024-03-27.10:50:16" },
    { name: "University of South Alabama - School of Computing - South Biomedical Informatics (SBI) Research Group", url: "http://biomedical.cis.usouthal.edu/" },
    { name: "University of Texas Southwestern Medical Center", url: "http://www.utsouthwestern.edu/" },
    { name: "University of Washington - Structural Informatics Group (SIG)", url: "http://sig.biostr.washington.edu/" },
    { name: "Visual Analytics (VA) tools for Sustainable Lifecycle Design (SLD)", url: "https://scispace.com/pdf/visual-analytics-tools-for-sustainable-lifecycle-design-4nfclcmcpe.pdf" },
    { name: "Virus Pathogen Resource (ViPR)", url: "https://www.viprbrc.org/brc/home.spg?decorator=vipr" },
    { name: "VIVO", url: "http://vivoweb.org/" },
    { name: "Volley: AI-powered learning hub", url: "http://volley.com/" },
    { name: "WTI Solutions", url: "https://www.wti-solutions.com/data-fusion/" }
  ],
  "Good Ontology Design (GoodOD)": [
    {
      name: "Department of Defence and Intelligence Community Ontology Working Group (DIOWG)",
      url: "https://basic-formal-ontology.org/Groups%20and%20Projects"
    },
    {
      name: "National Geospatial-Intelligence Agency (NGA)",
      url: "https://www.nga.mil/"
  }
]
};

  return (
    <Layout title="Users" description="Ontologies, institutions, and projects using BFO">
      <div className="container margin-vert--lg">
        <h1>Users of BFO</h1>
        <p>
          Below you will find an alphabetical list of <strong>ontologies</strong>,{' '}
          <strong>institutions, groups and projects</strong>, and{' '}
          <strong>Good Ontology Design (GoodOD)</strong> initiatives that use or support the Basic Formal Ontology.
        </p>
        <p>
          <strong>Jump to:</strong>{' '}
          <a href="#ontologies">Ontologies</a> |{' '}
          <a href="#institutions-groups-and-projects">Institutions, Groups and Projects</a> |{' '}
          <a href="#good-ontology-design-goodod">GoodOD</a>
        </p>
        <input
          type="text"
          placeholder="Search users..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          style={{
            padding: '0.5rem',
            width: '100%',
            maxWidth: 400,
            margin: '1rem 0',
            borderRadius: '6px',
            border: '1px solid #ccc'
          }}
        />
        {Object.entries(userData).map(([category, items]) => {
          const anchorId = category.toLowerCase().replace(/\s+/g, '-').replace(/[()]/g, '');
          const filtered = items.filter((item) =>
            item.name.toLowerCase().includes(search.toLowerCase())
          );

          if (filtered.length === 0) return null;
          return (
            <div key={category}>
              <div id={anchorId} />
              <details open className="margin-bottom--md">
                <summary style={{ fontSize: '1.2rem', fontWeight: 'bold', cursor: 'pointer' }}>
                  {category}
                </summary>
                <ul>
                  {filtered
                    .sort((a, b) => a.name.localeCompare(b.name))
                    .map((item, idx) => (
                      <li key={idx}>
                        {item.url ? (
                          <a href={item.url} target="_blank" rel="noopener noreferrer">
                            {item.name}
                          </a>
                        ) : (
                          item.name
                        )}
                      </li>
                    ))}
                </ul>
              </details>
            </div>
          );
        })}
      </div>
    </Layout>
  );
};
